// <auto-generated />
namespace UKSSDC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Adddatatime2torecords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adddatatime2torecords));
        
        string IMigrationMetadata.Id
        {
            get { return "201508070947508_Adddatatime2torecords"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
