// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace UKSSDC.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddOutwardCodeToPostcodes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddOutwardCodeToPostcodes));
        
        string IMigrationMetadata.Id
        {
            get { return "201601020304366_AddOutwardCodeToPostcodes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
